/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jeffreysanti.fractalengine;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowEvent;
import java.util.List;

/**
 *
 * @author jeffrey
 */
public class AnimationSelectKF extends javax.swing.JFrame {

    /**
     * Creates new form AnimationSelectKF
     */
    public AnimationSelectKF(AnimationWindow awnd) {
        mainWnd = awnd;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        paramList = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        frameNo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnOK = new javax.swing.JToggleButton();
        btnCancel = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select Keyframe");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Field:");
        jPanel1.add(jLabel1);

        paramList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(paramList);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Frame:");
        jPanel2.add(jLabel2);

        frameNo.setText("jTextField1");
        jPanel2.add(frameNo);

        getContentPane().add(jPanel2);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        jPanel3.add(btnOK);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancel);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        try{
            int fNo = Integer.parseInt(frameNo.getText());
            if(fNo > maxFrame || fNo < 2)
                return;
            mainWnd.frameSelected((String)paramList.getSelectedItem(), fNo);
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }catch(Exception ex){
            
        }
    }//GEN-LAST:event_btnOKActionPerformed
    
    public void setUp(List<String> l, int maxFrame){
        this.maxFrame = maxFrame;
        paramList.removeAllItems();
        for(String s : l){
            paramList.addItem(s);
        }
        frameNo.setText("2");
        jLabel1.setForeground(Color.BLACK);
        jLabel2.setForeground(Color.BLACK);
        
        this.pack();
        
        frameNo.addKeyListener(new KeyListener(){
            @Override
            public void keyTyped(KeyEvent ke) { }
            @Override
            public void keyPressed(KeyEvent ke) {  }
            @Override
            public void keyReleased(KeyEvent ke) {
                String val = frameNo.getText();
                jLabel2.setForeground(Color.RED);
                try{
                    int fNo = Integer.parseInt(frameNo.getText());
                    if(fNo <= AnimationSelectKF.this.maxFrame || fNo >= 2){
                        jLabel2.setForeground(Color.BLACK); // all OK
                    }
                }catch(Exception ex){

                }
            }
         });
    }
    
    private AnimationWindow mainWnd;
    private int maxFrame;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCancel;
    private javax.swing.JToggleButton btnOK;
    private javax.swing.JTextField frameNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox paramList;
    // End of variables declaration//GEN-END:variables
}
